name: Java CI with Maven

on:
  push:
    branches:
      - Feature/Github-test
  pull_request:
    branches:
      - Feature/Github-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      working-directory: Github_Actions
      run: mvn clean install -DskipTests

    - name: Run tests with Maven
      working-directory: Github_Actions
      run: mvn test