name: Java CI with Maven

on:
  push:
    branches:
      - Feature/Github-test
  pull_request:
    branches:
      - Feature/Github-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Descarga tu repositorio
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4  # Configura el JDK 17
        with:
          java-version: '17'  # Especifica la versión de Java
          distribution: 'temurin'

      - name: Change directory to Github_Actions and build with Maven
        run: |
          cd Github_Actions  # Cambia al directorio donde está el pom.xml
          mvn clean install -DskipTests  # Ejecuta Maven

      - name: Run tests with Maven
        run: mvn test  # Ejecuta las pruebas unitarias definidas en tu proyecto